version: '3.8'

services:

  backend:
    build:
      context: ./apps/backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/app
    env_file:
      - ./apps/backend/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  acheteur-app:
    build:
      context: ./apps/acheteur-app
    container_name: acheteur-app
    ports:
      - "3000:3000"
    volumes:
      - ./apps/acheteur-app:/app
    command: pnpm dev
    working_dir: /app
    env_file:
      - ./apps/acheteur-app/.env

  vendeur-app:
    build:
      context: ./apps/vendeur-app
    container_name: vendeur-app
    ports:
      - "3001:3000"
    volumes:
      - ./apps/vendeur-app:/app
    command: pnpm dev
    working_dir: /app
    env_file:
      - ./apps/vendeur-app/.env

  welcome-app:
    build:
      context: ./apps/welcome-app
    container_name: welcome-app
    ports:
      - "3002:3000"
    volumes:
      - ./apps/welcome-app:/app
    command: pnpm dev
    working_dir: /app
    env_file:
      - ./apps/welcome-app/.env

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: commerc_db
      POSTGRES_USER: commerc_user
      POSTGRES_PASSWORD: commerc_pass
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - acheteur-app
      - vendeur-app
      - welcome-app
      - backend

volumes:
  postgres_data:
